#!/bin/sh                                                                                  

/usr/bin/rsync -aSHPv --delete --delete-excluded --exclude=.git/objects/ --exclude='copying.tmp/' sundries01::docs/ /srv/web/docs.fedoraproject.org/
/usr/bin/rsync -aSHPv --delete --delete-excluded --exclude=.git/objects/ --exclude='copying.tmp/' sundries01::docs-redirects/ /srv/web/docs-redirects/

# build the combined docs tree. 
# See https://pagure.io/fedora-infrastructure/issue/7130

rsync -aH --delete /srv/web/docs.fedoraproject.org/ /srv/web/docs-redirects/ /srv/web/docs-old.fedoraproject.org/public_html/ /srv/web/docs-combined/
